name: dist-check
on:
  push:
    branches:
      - main

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build dist
        run: 'python setup.py sdist

          '
      - id: measurement-4
        name: Record Measurement After Build dist
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build dist
          task: get-measurement
      - name: Twine check
        run: 'pip install twine

          last_dist=$(ls -t dist/autoPyTorch-*.tar.gz | head -n 1)

          twine check "$last_dist" --strict

          '
      - id: measurement-6
        name: Record Measurement After Twine check
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Twine check
          task: get-measurement
      - name: Install dist
        run: 'last_dist=$(ls -t dist/autoPyTorch-*.tar.gz | head -n 1)

          pip install $last_dist

          '
      - id: measurement-8
        name: Record Measurement After Install dist
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dist
          task: get-measurement
      - name: PEP 561 Compliance
        run: 'pip install mypy


          cd ..  # required to use the installed version of autoPyTorch


          # Note this doesn''t perform mypy checks, those are handled in pre-commit.yaml

          # This only checks if autoPyTorch exports type information

          if ! mypy -c "import autoPyTorch"; then exit 1; fi

          '
      - id: measurement-10
        name: Record Measurement After PEP 561 Compliance
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: PEP 561 Compliance
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
